name: Static Code Analysis

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  analyse:
    name: Static Code Analysis
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Copy env example for initial composer setup
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: gd
        env:
          APP_ENV: analysis

      - name: Trying to Restore Packages From Cache
        id: cache-packages
        uses: actions/cache/restore@v4
        with:
          path: vendor
          key: packages-cache-${{ hashFiles('composer.lock') }}

      - name: Trying to Restore Result Cache For Analyzer
        uses: actions/cache/restore@v4
        with:
          path: /tmp/phpstan
          key: analysis-result-cache-${{ github.run_id }}
          restore-keys: |
            analysis-result-cache-

      - name: Install Dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: composer
          --no-scripts
          --no-interaction
          --prefer-dist
          --ignore-platform-req=ext-zip
          --ignore-platform-req=ext-imagick
          --ignore-platform-req=ext-bcmath
          --ignore-platform-req=ext-gd
          --ignore-platform-req=ext-pcntl
          --ignore-platform-req=ext-rdkafka
          --ignore-platform-req=ext-sockets
          --ignore-platform-req=ext-elastic_apm
          install

      - name: Analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 2G

      - name: "Save packages cache"
        uses: actions/cache/save@v4
        if: steps.cache-packages.outputs.cache-hit != 'true'
        with:
          path: vendor
          key: packages-cache-${{ hashFiles('composer.lock') }}

      - name: "Save analysis result cache"
        uses: actions/cache/save@v4
        with:
          path: /tmp/phpstan
          key: analysis-result-cache-${{ github.run_id }}
