name: PR Test

on:
  push:
    branches:
      - main

jobs:
  pr_test:
    name: Create PR Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy env example for initial composer setup
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: gd

      - name: Install Dependencies
        run: APP_ENV=analysis composer
          --ignore-platform-req=ext-zip
          --ignore-platform-req=ext-imagick
          --ignore-platform-req=ext-bcmath
          --ignore-platform-req=ext-gd
          --ignore-platform-req=ext-pcntl
          --ignore-platform-req=ext-rdkafka
          --ignore-platform-req=ext-sockets
          --ignore-platform-req=ext-elastic_apm
          install

      - name: Generating Baseline
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=2G --allow-empty-baseline --generate-baseline phpstan-baseline.neon

      - name: Create commit
        run: |
          git config user.name 'StaticAnalysis'
          git config user.email 'aliaksandr.gg+analyzer@gmail.com'
          git commit -am "Updated code analyzer baseline"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TEST }}
          branch: baseline-update
          delete-branch: true
          title: '[AUTO] Updated code analyzer baseline'
